name: Test Docker Build
on:
  push:
    branches-ignore:
      - main

jobs:
  endpoint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [ newreno, nocc]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply variants patch
        run: |
          ls -la
          (test -f variants/${{ matrix.variant }}/*.patch && git apply variants/${{ matrix.variant }}/*.patch) || echo no patch, skipping

      - name: Build Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
